# -*- coding: utf-8 -*-
"""块3·脚本A（maple，BOM/LF）：后脑勺抓梯/到顶/卡住监管 的常量、字段、复位与方法骨架。
   - 后脑判据 _back_head_visible（只读A线程写的 _role_last_scores['back']）
   - 抓住收口 _grab_to_climbing（跑跳/直跳/校准直跳共用）
   - 主线解卡相位 _ladder_stuck_recover_tick（非阻塞、不sleep、不自递归）
   - 监管线程 _wd_check_ladder_stuck（只置令 _ladder_stuck_cmd，绝不发键），挂进 _wd_check_once
   本脚本只新增，不改既有判定（判定在脚本B/C改）。"""
import io
import py_compile

P = r'C:\Users\wenwen\Desktop\MXD\maple_bot_v2\maple_route_ui.py'
b = io.open(P, 'rb').read()
assert b.startswith(b'\xef\xbb\xbf'), 'maple 缺 BOM'
raw = b[3:].decode('utf-8')
assert '\r\n' not in raw, 'maple 出现 CRLF'

# ---------- 1) 常量（LADDER_REALIGN_NO_TPL_MS 后） ----------
anchor_const = "LADDER_REALIGN_NO_TPL_MS = 1200   # 校准直跳里连续多久拿不到梯子屏幕X(无模板/匹配不到)=回主线,不死等\n"
const_block = anchor_const + (
    "# === 后脑勺抓梯/到顶/卡住监管(用户2026-09-18定稿:人在梯子上(上爬/下爬)才看得到后脑勺,自由落体/下平台/地面看不到;\n"
    "#   抓住=起跳后连续2帧看到后脑;到顶=climbing中连续250ms看不到后脑(已翻出台子,再补按↑LADDER_TOP_HOLD_MS翻稳),\n"
    "#   小地图光点重合梯端+录梯时长超时仅作兜底;卡住=后脑在梯但小地图光点Y连续2s不动→监管线程只置令、主线climbing非阻塞横跳解卡)。仅上梯direction>0生效 ===\n"
    "BACK_ON_LADDER_THR = 0.55       # 后脑勺\"在梯子上\"分数阈(定位thr约0.62,在梯判定单独0.55;真机看[爬梯·后脑]日志分数再微调)\n"
    "BACK_GRAB_FRAMES = 2            # 起跳后连续几帧看到后脑=抓住梯子(抗单帧误检)\n"
    "BACK_TOP_LOST_MS = 250          # climbing中连续多久看不到后脑=翻出平台到顶\n"
    "LADDER_STUCK_MS = 2000          # 卡住:后脑在梯且光点Y连续多久不动(小地图系)\n"
    "LADDER_STUCK_DOT_DY = 2.0       # 光点Y(小地图px)变化小于此=没动(卡住静止/解卡后恢复移动判据共用)\n"
    "LADDER_STUCK_SIDE_MS = 120      # 解卡:固定按右方向键时长\n"
    "LADDER_STUCK_JUMP_MS = 120      # 解卡:跳键保持时长\n"
    "LADDER_STUCK_SETTLE_MS = 450    # 解卡横跳后落地/重挂观察窗(一次腾空约360ms+余量)\n"
    "LADDER_STUCK_COOLDOWN_MS = 2500 # 两次横跳解卡之间的冷却\n"
    "LADDER_STUCK_MAX_FAILS = 3      # 连续解卡几次仍卡=放弃这把梯回打怪/重选\n"
)

# ---------- 2) __init__ 字段（1355 两步法确认字段后） ----------
anchor_init = "        self._climb_move_confirmed = False             # 两步法第一步:是否已确认\"真的在爬\"(三背景点至少出现过一次在动);未确认前静止=起步,不判到顶\n"
init_block = anchor_init + (
    "        # === 后脑勺抓梯/到顶/卡住监管运行态(用户2026-09-18;每次_reset_climb复位) ===\n"
    "        self._ladder_back_seen_frames = 0      # 起跳后连续看到后脑的帧数(抓住判据)\n"
    "        self._ladder_back_lost_since = 0       # climbing中后脑连续不可见起始ms(0=当前可见)\n"
    "        self._ladder_back_top = False          # 后脑连续BACK_TOP_LOST_MS不可见=已翻出台子到顶\n"
    "        self._ladder_back_diag_t = 0           # 后脑分数诊断日志节流\n"
    "        self._climb_top_hold_why = \"\"          # 到顶hold由哪个判据触发(后脑/光点)\n"
    "        self._ladder_stuck_phase = None        # 主线解卡相位 None/start/right/jump/settle\n"
    "        self._ladder_stuck_t = 0               # 解卡当前相位起始ms\n"
    "        self._ladder_stuck_jump_vk = None      # 解卡跳键vk(非阻塞keydown/keyup)\n"
    "        self._ladder_stuck_cmd = None          # 监管线程→主线·卡住令{'t','y'}/None(监管只置令)\n"
    "        self._ladder_stuck_last_y = None       # 监管:上一次光点Y(小地图),动了就更新\n"
    "        self._ladder_stuck_motion_since = 0    # 监管:光点Y静止起始ms\n"
    "        self._ladder_stuck_fails = 0           # 本轮爬梯连续横跳解卡失败次数\n"
    "        self._ladder_stuck_cooldown_until = 0  # 解卡失败后再试冷却截止ms\n"
)

# ---------- 3) _reset_climb 复位（4866 到顶补按复位行后） ----------
anchor_reset = "        self._climb_top_hold = False         # 到顶补按200ms子态复位\n"
reset_block = anchor_reset + (
    "        # 后脑勺抓梯/到顶/卡住监管状态复位(用户2026-09-18)\n"
    "        self._ladder_back_seen_frames = 0\n"
    "        self._ladder_back_lost_since = 0\n"
    "        self._ladder_back_top = False\n"
    "        self._ladder_back_diag_t = 0\n"
    "        self._climb_top_hold_why = \"\"\n"
    "        self._ladder_stuck_phase = None\n"
    "        self._ladder_stuck_t = 0\n"
    "        self._ladder_stuck_jump_vk = None\n"
    "        self._ladder_stuck_cmd = None\n"
    "        self._ladder_stuck_last_y = None\n"
    "        self._ladder_stuck_motion_since = 0\n"
    "        self._ladder_stuck_fails = 0\n"
    "        self._ladder_stuck_cooldown_until = 0\n"
)

# ---------- 4) 爬梯方法（插在 _ladder_post_jump_process 前） ----------
anchor_postjump = "    def _ladder_post_jump_process(self, py, now_ms):\n"
methods = (
    "    def _back_head_visible(self):\n"
    "        \"\"\"后脑勺是否可见=人物是否在梯子上(用户2026-09-18:上爬/下爬梯子都看得到后脑,自由落体/下平台/地面看不到)。\n"
    "        人物识别A线程每帧把各锚点写入 self._role_last_scores['back']=(分数,(x,y),朝向),本方法跨线程只读最新值。\n"
    "        返回(是否在梯, 分数);无锚点数据/低于BACK_ON_LADDER_THR → (False, 分数)。\"\"\"\n"
    "        try:\n"
    "            got = getattr(self, '_role_last_scores', None)\n"
    "            if not got:\n"
    "                return False, 0.0\n"
    "            b = got.get('back')\n"
    "            if not b:\n"
    "                return False, 0.0\n"
    "            s = float(b[0])\n"
    "            loc = b[1] if len(b) > 1 else None\n"
    "            if loc is None:\n"
    "                return False, s\n"
    "            return (s >= BACK_ON_LADDER_THR), s\n"
    "        except Exception:\n"
    "            return False, 0.0\n"
    "\n"
    "    def _grab_to_climbing(self, via, py, now_ms, score):\n"
    "        \"\"\"起跳后连续BACK_GRAB_FRAMES帧看到后脑勺=已挂上梯子(用户2026-09-18,取代旧\"起跳前后光点Y变小\"判据)。\n"
    "        跑跳/直跳/校准直跳抓住后统一从这里转climbing:清攻击+左右只留↑、复位到顶/卡住后脑状态,新一轮在梯计时清零。\"\"\"\n"
    "        self._release_move_conflicts()\n"
    "        if VK_DOWN in self._random_move_keys:\n"
    "            self._key_up(VK_DOWN)\n"
    "        if VK_UP not in self._random_move_keys:\n"
    "            self._key_down(VK_UP)\n"
    "        self._climb_state = 'climbing'\n"
    "        self._climb_action_time = now_ms\n"
    "        self._climb_start_y = py\n"
    "        self._climb_move_confirmed = False\n"
    "        self._climb_still_since = 0\n"
    "        self._climb_top_hold = False\n"
    "        self._climb_top_hold_t = 0\n"
    "        self._climb_top_hold_why = \"\"\n"
    "        self._ladder_jump_phase = None\n"
    "        self._ladder_post_jump_step = None\n"
    "        # 新一轮在梯:后脑到顶/卡住监管计时全部清零重计\n"
    "        self._ladder_back_seen_frames = 0\n"
    "        self._ladder_back_lost_since = 0\n"
    "        self._ladder_back_top = False\n"
    "        self._ladder_stuck_phase = None\n"
    "        self._ladder_stuck_cmd = None\n"
    "        self._ladder_stuck_last_y = None\n"
    "        self._ladder_stuck_motion_since = 0\n"
    "        self._ladder_stuck_fails = 0\n"
    "        self._ladder_stuck_cooldown_until = 0\n"
    "        _end_y = self._climb_ladder_y_top if self._climb_direction > 0 else self._climb_ladder_y_bottom\n"
    "        _debug_log(\"[爬梯·后脑] %s连续%d帧看到后脑(%.2f)=抓住,转持续爬(光点Y=%.0f 梯端Y=%.0f)\" % (\n"
    "            via, BACK_GRAB_FRAMES, score, py, _end_y or 0))\n"
    "        self._rlog(\"%s抓住梯子(后脑判据),持续向%s到顶\" % (\n"
    "            via, \"上\" if self._climb_direction > 0 else \"下\"), LOG_OK, log='behavior')\n"
    "\n"
    "    def _ladder_stuck_clear(self):\n"
    "        \"\"\"清卡住令/解卡相位/静止计时(失败次数fails与冷却由调用方按出口处理)。\"\"\"\n"
    "        self._ladder_stuck_cmd = None\n"
    "        self._ladder_stuck_phase = None\n"
    "        self._ladder_stuck_jump_vk = None\n"
    "        self._ladder_stuck_last_y = None\n"
    "        self._ladder_stuck_motion_since = 0\n"
    "\n"
    "    def _ladder_stuck_recover_tick(self, px, py, now_ms):\n"
    "        \"\"\"主线climbing消费卡住令(非阻塞相位,不sleep、不自递归;用户2026-09-18):\n"
    "        松↑↓左右→固定按右键LADDER_STUCK_SIDE_MS→跳LADDER_STUCK_JUMP_MS(梯上横跳脱)→落地/重挂观察SETTLE→三出口:\n"
    "        A 后脑消失=离梯落地,按到顶重锁怪开打;B 后脑在但光点Y恢复动=重新可爬,回climbing接着爬(不重新对位/跑跳);\n"
    "        C 后脑在Y仍不动=本次失败,未满3次冷却后再试、满3次放弃这把梯回打怪/重选。\"\"\"\n"
    "        ph = self._ladder_stuck_phase\n"
    "        if ph == 'start':\n"
    "            for _vk in (VK_UP, VK_DOWN, VK_LEFT, VK_RIGHT):\n"
    "                if _vk in self._random_move_keys:\n"
    "                    self._key_up(_vk)\n"
    "            self._ladder_stuck_phase = 'right'\n"
    "            self._ladder_stuck_t = now_ms\n"
    "            self._key_down(VK_RIGHT)  # 卡梯横跳固定朝右(用户指定)\n"
    "            _debug_log(\"[爬梯解卡] 开始:松键后固定按右键%dms再跳\" % LADDER_STUCK_SIDE_MS)\n"
    "            return False\n"
    "        if ph == 'right':\n"
    "            if now_ms - self._ladder_stuck_t >= LADDER_STUCK_SIDE_MS:\n"
    "                self._key_up(VK_RIGHT)\n"
    "                _jk = self._get_fight_config().get('jump_key', '')\n"
    "                self._ladder_stuck_jump_vk = self._key_to_vk(_jk) if _jk else None\n"
    "                if self._ladder_stuck_jump_vk is not None:\n"
    "                    self._send_win_key(self._ladder_stuck_jump_vk, keyup=False)\n"
    "                self._ladder_stuck_phase = 'jump'\n"
    "                self._ladder_stuck_t = now_ms\n"
    "                _debug_log(\"[爬梯解卡] 右键%dms到,起跳横跳\" % LADDER_STUCK_SIDE_MS)\n"
    "            return False\n"
    "        if ph == 'jump':\n"
    "            if now_ms - self._ladder_stuck_t >= LADDER_STUCK_JUMP_MS:\n"
    "                if getattr(self, '_ladder_stuck_jump_vk', None) is not None:\n"
    "                    self._send_win_key(self._ladder_stuck_jump_vk, keyup=True)\n"
    "                    self._ladder_stuck_jump_vk = None\n"
    "                self._ladder_stuck_phase = 'settle'\n"
    "                self._ladder_stuck_t = now_ms\n"
    "            return False\n"
    "        # settle:横跳腾空/落地观察窗,期间不按键\n"
    "        if now_ms - self._ladder_stuck_t < LADDER_STUCK_SETTLE_MS:\n"
    "            return False\n"
    "        bv, _bs = self._back_head_visible()\n"
    "        _cmd = getattr(self, '_ladder_stuck_cmd', None) or {}\n"
    "        _y0 = _cmd.get('y')\n"
    "        _dy = abs(float(py) - float(_y0)) if _y0 is not None else 0.0\n"
    "        if not bv:\n"
    "            # 出口A:后脑消失=离梯落地,按到顶收尾、立刻重锁怪开打\n"
    "            _debug_log(\"[爬梯解卡] 横跳后后脑消失=离梯落地,按到顶重锁怪开打\")\n"
    "            self._rlog(\"卡梯横跳已离梯,落地开打\", LOG_OK, log='behavior')\n"
    "            for _vk in (VK_UP, VK_DOWN, VK_LEFT, VK_RIGHT):\n"
    "                if _vk in self._random_move_keys:\n"
    "                    self._key_up(_vk)\n"
    "            self._ladder_stuck_clear()\n"
    "            self._reset_climb()\n"
    "            self._reset_lock_after_arrival('卡梯横跳落地')\n"
    "            return False\n"
    "        if _dy >= LADDER_STUCK_DOT_DY:\n"
    "            # 出口B:后脑在但光点Y恢复动=重新可爬,回climbing从中断处接着爬(不重新对位/跑跳)\n"
    "            _debug_log(\"[爬梯解卡] 横跳后后脑在、光点Y恢复移动(Δ%.1f),回climbing继续爬\" % _dy)\n"
    "            self._rlog(\"解卡后恢复移动,继续爬梯\", log='behavior')\n"
    "            self._ladder_stuck_clear()\n"
    "            self._ladder_back_lost_since = 0\n"
    "            return False\n"
    "        # 出口C:后脑在、Y仍不动=本次解卡失败\n"
    "        self._ladder_stuck_fails = getattr(self, '_ladder_stuck_fails', 0) + 1\n"
    "        if self._ladder_stuck_fails >= LADDER_STUCK_MAX_FAILS:\n"
    "            _debug_log(\"[爬梯解卡] 连续%d次横跳仍卡(后脑在Y不动),放弃这把梯回主线打怪/重选\" % self._ladder_stuck_fails)\n"
    "            self._rlog(\"爬梯卡住解卡%d次不成,放弃回打怪\" % self._ladder_stuck_fails, LOG_RED, log='exception')\n"
    "            self._ladder_stuck_clear()\n"
    "            self._climb_fail_pause_until = now_ms + LADDER_FAIL_REENTER_MS\n"
    "            self._reset_climb()\n"
    "            self._decide_climb_fail_action()\n"
    "            return False\n"
    "        self._ladder_stuck_cooldown_until = now_ms + LADDER_STUCK_COOLDOWN_MS\n"
    "        _debug_log(\"[爬梯解卡] 第%d次横跳后仍卡,%dms冷却后再试\" % (self._ladder_stuck_fails, LADDER_STUCK_COOLDOWN_MS))\n"
    "        self._ladder_stuck_clear()\n"
    "        return False\n"
    "\n"
    + anchor_postjump)

# ---------- 5) 监管检测方法 + _wd_check_once 末尾调用（_move_watchdog_loop 前） ----------
anchor_wd = "color=LOG_RED)\n\n    def _move_watchdog_loop(self):\n"
wd_method = (
    "    def _wd_check_ladder_stuck(self):\n"
    "        \"\"\"爬梯卡住监管(独立监管线程,用户2026-09-18):仅上梯climbing(direction>0)、【后脑勺可见=确在梯上】且小地图光点Y\n"
    "        连续LADDER_STUCK_MS几乎不动(变化<LADDER_STUCK_DOT_DY)=卡在梯上。只置令 self._ladder_stuck_cmd,绝不发键\n"
    "        (物理横跳统一由主线climbing的_ladder_stuck_recover_tick执行,与边界守护同一套'监管置令、主线发键',不抢主权)。\n"
    "        下行/正在解卡/令未消费/冷却窗/已达放弃次数 都不检测。全程try自保护,绝不崩主线。\"\"\"\n"
    "        try:\n"
    "            now = time.time() * 1000\n"
    "            if getattr(self, '_climb_state', 'none') != 'climbing' or getattr(self, '_climb_direction', 0) <= 0:\n"
    "                self._ladder_stuck_last_y = None\n"
    "                self._ladder_stuck_motion_since = 0\n"
    "                return\n"
    "            if getattr(self, '_ladder_stuck_phase', None) is not None:\n"
    "                return  # 主线正在解卡,不重复检测\n"
    "            if getattr(self, '_ladder_stuck_cmd', None) is not None:\n"
    "                return  # 令还没被主线消费\n"
    "            if now < getattr(self, '_ladder_stuck_cooldown_until', 0):\n"
    "                return\n"
    "            if getattr(self, '_ladder_stuck_fails', 0) >= LADDER_STUCK_MAX_FAILS:\n"
    "                return\n"
    "            bv, _bs = self._back_head_visible()\n"
    "            mp = getattr(self, '_player_map_pos', None)\n"
    "            if (not bv) or mp is None:\n"
    "                self._ladder_stuck_last_y = None\n"
    "                self._ladder_stuck_motion_since = 0\n"
    "                return  # 后脑不在=不在梯上(到顶翻出/地面),谈不上卡梯\n"
    "            try:\n"
    "                y = float(mp[1])\n"
    "            except Exception:\n"
    "                return\n"
    "            if self._ladder_stuck_last_y is None:\n"
    "                self._ladder_stuck_last_y = y\n"
    "                self._ladder_stuck_motion_since = now\n"
    "                return\n"
    "            if abs(y - self._ladder_stuck_last_y) >= LADDER_STUCK_DOT_DY:\n"
    "                self._ladder_stuck_last_y = y       # 真在往上爬:更新基准、静止计时清零\n"
    "                self._ladder_stuck_motion_since = now\n"
    "                return\n"
    "            if self._ladder_stuck_motion_since == 0:\n"
    "                self._ladder_stuck_motion_since = now\n"
    "            if now - self._ladder_stuck_motion_since >= LADDER_STUCK_MS:\n"
    "                self._ladder_stuck_cmd = {'t': now, 'y': self._ladder_stuck_last_y}\n"
    "                _debug_log(\"[监管线] 爬梯卡住:后脑在梯但光点Y=%.1f连续%.1fs不动,置令主线横跳解卡\" % (\n"
    "                    self._ladder_stuck_last_y, LADDER_STUCK_MS / 1000.0))\n"
    "                self._rlog(\"爬梯卡住(在梯%.0fs不动),横跳解卡\" % (LADDER_STUCK_MS / 1000.0), LOG_RED, log='exception')\n"
    "        except Exception as e:\n"
    "            try:\n"
    "                _debug_log(\"[监管线] 爬梯卡住检测异常: %s\" % e)\n"
    "            except Exception:\n"
    "                pass\n"
    "\n"
)
wd_block = (
    "color=LOG_RED)\n"
    "        # 爬梯卡住监管(每拍独立检测、只置令不发键;用户2026-09-18)\n"
    "        self._wd_check_ladder_stuck()\n"
    "\n"
    + wd_method
    + "    def _move_watchdog_loop(self):\n"
)

pairs = [
    (anchor_const, const_block),
    (anchor_init, init_block),
    (anchor_reset, reset_block),
    (anchor_postjump, methods),
    (anchor_wd, wd_block),
]
for i, (o, n) in enumerate(pairs, 1):
    c = raw.count(o)
    assert c == 1, '锚点%d 命中%d次(应为1),中止' % (i, c)
    raw = raw.replace(o, n)

io.open(P, 'wb').write(b'\xef\xbb\xbf' + raw.encode('utf-8'))
py_compile.compile(P, doraise=True)
print('BLOCK3-A maple OK(常量/字段/复位/4方法/监管挂载), py_compile pass')
